### ISSUE TITLE
External Links: 'SharedConfig' object has no attribute 'lapl'

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#212]
_Original author: thomas.r...@gmail.com (July 27, 2011 22:06:09)_

The following script:

import h5py

f = h5py.File('original.hdf5', 'w')
f.create_group('a')
f.close()

g = h5py.File('new.hdf5', 'w')
g['link'] = h5py.ExternalLink('original.hdf5', '/')
g.close()

h = h5py.File('new.hdf5', 'r')
print h['link']['a']

causes the following exception:

Traceback (most recent call last):
  File &quot;testhdf5.py&quot;, line 12, in &lt;module&gt;
    print h['link']['a']
  File &quot;/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/group.py&quot;, line 127, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._shared.lapl)
AttributeError: 'SharedConfig' object has no attribute 'lapl'

I am using MacOS 10.6.7, Python 2.7, HDF5 1.8.7 (macports), h5py 2.0.0. I used not to have this issue, but it started after I upgraded to 2.0.0. Is there a workaround I can use for now? Thanks!

_Original issue: http://code.google.com/p/h5py/issues/detail?id=212_
