### ISSUE TITLE
Test failure with HDF5 1.12 on master

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1545]
We may have been too quick to declare success with PR #1506 . It's failing to build in master with HDF5 1.12:

```
    gcc -pthread -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.8.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.8.2/x64/lib build/temp.linux-x86_64-3.8/tmp/pip-req-build-lm5xfcqn/h5py/h5g.o -L/home/vsts/work/1/cache/hdf5/1.12.0/lib -L/opt/hostedtoolcache/Python/3.8.2/x64/lib -Wl,--enable-new-dtags,-R/home/vsts/work/1/cache/hdf5/1.12.0/lib -lhdf5 -lhdf5_hl -o build/lib.linux-x86_64-3.8/h5py/h5g.cpython-38-x86_64-linux-gnu.so
    building 'h5py.h5l' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DH5_USE_16_API -DNPY_NO_DEPRECATED_API=0 -I./h5py -I/home/vsts/work/1/cache/hdf5/1.12.0/include -I/tmp/pip-req-build-lm5xfcqn/lzf -I/home/vsts/work/1/s/.tox/py38-test-deps/lib/python3.8/site-packages/numpy/core/include -I/home/vsts/work/1/s/.tox/py38-test-deps/include -I/opt/hostedtoolcache/Python/3.8.2/x64/include/python3.8 -c /tmp/pip-req-build-lm5xfcqn/h5py/h5l.c -o build/temp.linux-x86_64-3.8/tmp/pip-req-build-lm5xfcqn/h5py/h5l.o
    /tmp/pip-req-build-lm5xfcqn/h5py/h5l.c: In function ‘__pyx_pf_4h5py_3h5l_8LinkInfo_1u___get__’:
    /tmp/pip-req-build-lm5xfcqn/h5py/h5l.c:2611:68: error: ‘union <anonymous>’ has no member named ‘address’
         __pyx_t_2 = __Pyx_PyInt_From_haddr_t(__pyx_v_self->infostruct.u.address); if (unlikely(!__pyx_t_2)) __PYX_ERR(1, 53, __pyx_L1_error)
```

It looks like the `H5L_info_t` struct was removed in HDF5 1.12.

Why didn't we notice this before merging the PR? At an educated guess, when we removed the `--with-default-api-version=v110` flag, the Azure cache still contained HDF5 built with that flag, and it didn't get rebuilt, so the next test run still used it. Once in master, it didn't use that cache any more, so the tests failed.

In principle, the cache key should include the file `ci/travis/get_hdf5_if_needed.sh`, so changing that file invalidates the cache. But as it's never modified any options before, it didn't introduce any variation, so we were satisfied with keying on the platform & version number.

**Comment by takluyver** [comment]
Oh, but I think #1542 fixes the test failure.

**Comment by takluyver** [comment]
Fixed in master
