### ISSUE TITLE
h5py 3.0 incompatibility with TensorFlow model serialization (multiple versions)

### ISSUE THREAD

**Issue by tgaddair** [h5py/h5py#1732]
* Operating System: Linux (Ubuntu 18.04), macOS
 * Python version: 3.6, 3.7
 * Where Python was acquired: System (Linux), Pyenv (macOS)
 * h5py version: 3.0.0
 * HDF5 version: 1.12.0
 * The full traceback/stack trace shown:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    model.save('test.h5')
  File "/Users/tgaddair/.venv/horovod/stable/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1171, in save
    signatures)
  File "/Users/tgaddair/.venv/horovod/stable/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 109, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/Users/tgaddair/.venv/horovod/stable/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 103, in save_model_to_hdf5
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/Users/tgaddair/.venv/horovod/stable/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 625, in save_weights_to_hdf5_group
    param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
  File "/Users/tgaddair/.venv/horovod/stable/lib/python3.7/site-packages/h5py/_hl/group.py", line 143, in create_dataset
    if '/' in name:
TypeError: a bytes-like object is required, not 'str'
```

Here are the parameter values being passed from TensorFlow into `create_dataset`:

```
self = <Closed HDF5 group>, name = b'dense/kernel:0', shape = (3, 2)
dtype = dtype('float32'), data = None, kwds = {'track_order': False}
group = <Closed HDF5 group>
```

As you can see, TensorFlow is providing the name as bytes type, not a str, which seems to be the crux of the issue here.

Repro script (tested with TensorFlow 1.15.0 and 2.3.1):

```
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(2, input_shape=(3,)))
model.save('test.h5')
```

Rolling back to `h5py==2.10.0` works fine.

**Comment by takluyver** [comment]
[The docs](https://docs.h5py.org/en/stable/strings.html#object-names) do say that

> You can supply either byte or unicode strings when creating or retrieving objects.

So this is a bug.

**Comment by aarondav** [comment]
It would be awesome to get a patch release to resolve this -- unfortunately we're seeing the same issue from just installing tensorflow and serializing/deserializing models.

**Comment by takluyver** [comment]
Yup, I'm aiming to do another release this week, fixing several regressions that were only found after releasing 3.0.

**Comment by bhack** [comment]
@takluyver Do have any idea about https://github.com/tensorflow/tensorflow/pull/45380 fails?

Seems that something diverged between Linux and Win/Macosx with h5py 3.x. 
With exactly the same code we have now `AttributeError: 'str' object has no attribute 'decode'` but only on Win/Macosx

**Comment by bhack** [comment]
Just to point you to the error line https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/hdf5_format.py#L182

**Comment by takluyver** [comment]
Looks like that variable comes from an attribute. You can see the special string handling - deciding when to decode to str - here:

https://github.com/h5py/h5py/blob/95e3497e896e49192a6e46521fb7b9d4d526cf92/h5py/_hl/attrs.py#L79-L84

The rule is pretty simple: variable length strings in attributes are decoded, fixed length strings aren't. I don't think it should be platform dependent. I haven't looked at your tests, but is it possible that there is some difference affecting the code writing the file?

**Comment by bhack** [comment]
The save and load code is in the same file and seems to me without any platform condition. 
It was working ok with `h5py 2.10.0`. 
I really want to print inside `h5t.check_string_dtype` but I have not a Windows or Macos shell available.
Do you think there could be some new cases for 3.x where the `dtype` of the `attr` for `h5t.check_string_dtype` could be platform dependent?

**Comment by takluyver** [comment]
I'm not aware of anything in h5py that would make it platform dependent.

You might want to use `h5dump` (command line tool) to see what's really in the HDF5 file you're trying to read.
