### ISSUE TITLE
Cannot compile dynamic LZF filter plugin

### ISSUE THREAD

**Issue by u55** [h5py/h5py#1219]
Hi,
I am not able to compile the LZF dynamic filter plugin using the command listed in the README:
https://github.com/h5py/h5py/blob/9dc8048f98b7460b0fcb79b5d0b81005878ca036/lzf/README.txt#L62

I get the following error messages, and the `liblzf_filter.so` file is not created:
```bash
$ gcc -O2 -fPIC -shared lzf/*.c lzf_filter.c -o liblzf_filter.so
lzf_filter.c:79:5: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
     "lzf",
     ^~~~~
lzf_filter.c:79:5: note: (near initialization for ‘filter_class.id’)
lzf_filter.c:79:5: error: initializer element is not computable at load time
lzf_filter.c:79:5: note: (near initialization for ‘filter_class.id’)
lzf_filter.c:80:5: warning: initialization of ‘unsigned int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
     NULL,
     ^~~~
lzf_filter.c:80:5: note: (near initialization for ‘filter_class.encoder_present’)
lzf_filter.c:81:5: warning: initialization of ‘unsigned int’ from ‘herr_t (*)(hid_t,  hid_t,  hid_t)’ {aka ‘int (*)(long int,  long int,  long int)’} makes integer from pointer without a cast [-Wint-conversion]
     (H5Z_set_local_func_t)(lzf_set_local),
     ^
lzf_filter.c:81:5: note: (near initialization for ‘filter_class.decoder_present’)
lzf_filter.c:81:5: error: initializer element is not computable at load time
lzf_filter.c:81:5: note: (near initialization for ‘filter_class.decoder_present’)
lzf_filter.c:82:5: warning: initialization of ‘const char *’ from incompatible pointer type ‘size_t (*)(unsigned int,  size_t,  const unsigned int *, size_t,  size_t *, void **)’ {aka ‘long unsigned int (*)(unsigned int,  long unsigned int,  const unsigned int *, long unsigned int,  long unsigned int *, void **)’} [-Wincompatible-pointer-types]
     (H5Z_func_t)(lzf_filter)
     ^
lzf_filter.c:82:5: note: (near initialization for ‘filter_class.name’)
```
The LZF filter works fine for me in h5py, but I would like to use the filter plugin with the hdf5 command-line programs: h5dump, h5repack, h5diff, etc. Thanks.

Using: h5py git master branch
Operating System: Arch Linux
HDF5: version 1.10.5
gcc: version 8.3.0

**Comment by t20100** [comment]
The code of the lzf plugin is not taking care of hdf5 v1.10 and uses the wrong structure for defining the filter. 
To make it build with hdf51.10, add `-DH5_USE_16_API` (as is https://github.com/h5py/h5py/blob/master/setup_build.py#L47).
The code could be cleaned-up by removing hdf5 <1.8.4 support.

**Comment by takluyver** [comment]
I believe this has been fixed by #1458.
