### ISSUE TITLE
h5py.ipy_completer compatibility with ipython 8.12

### ISSUE THREAD

**Issue by anntzer** [h5py/h5py#2253]
```
Summary of the h5py configuration
---------------------------------

h5py    3.8.0
HDF5    1.12.2
Python  3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.24.2
cython (built with) 0.29.33
numpy (built against) 1.23.2
HDF5 (built against) 1.12.2
```

h5py.ipy_completer crashes ipython 8.12 when trying to tab-complete a dict key:
```
$ ipython --profile=null
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: null

In [1]: %load_ext h5py.ipy_completer

In [2]: d = {}

Traceback (most recent call last):
  File "/Users/antony/.local/lib/python3.11/site-packages/IPython/core/completer.py", line 3171, in _complete
    result = matcher(context)
             ^^^^^^^^^^^^^^^^
  File "/Users/antony/.local/lib/python3.11/site-packages/IPython/core/completer.py", line 2707, in custom_completer_matcher
    matches = self.dispatch_custom_completer(context.token) or []
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antony/.local/lib/python3.11/site-packages/IPython/core/completer.py", line 2747, in dispatch_custom_completer
    res = c(event)
          ^^^^^^^^
  File "/Users/antony/.local/lib/python3.11/site-packages/h5py/ipy_completer.py", line 131, in h5py_completer
    if not isinstance(self._ofind(base).get('obj'), (AttributeManager, HLObject)):
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OInfo' object has no attribute 'get'

If you suspect this is an IPython 8.12.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [3]: d[
```
The traceback above appears after typing `d[<TAB>`.
(The null profile is one I set up with no ipython customizations whatsoever).

**Comment by tacaswell** [comment]
Caused by https://github.com/ipython/ipython/pull/13973 which changed the from a dictionary to a class dict.

We can either adapt here or add a `get` method to IPython.

**Comment by Carreau** [comment]
Sure, I can add a get method. Sorry for the breakage.

**Comment by Carreau** [comment]
See ipython/ipython#14033, I had the feeling I was going to break something, but at the same time now OInfo is statically typed 😬

**Comment by Carreau** [comment]
(also should be this Friday release)
