### ISSUE TITLE
Can't read from HDF5 file: " TypeError: __init__() got an unexpected keyword argument 'readonly' "

### ISSUE THREAD

**Issue by Jballbe** [h5py/h5py#2275]
Hi,

I am trying to open an HDF5 file using your library (which worked perfectly up to now). However, since I updated several package, as well as Spyder IDE, and MacOS/XCode yesterday, I can't read some DataFrame I saved in this file.
My file is organized as follow:

- Cell_504120613_data_file.h5
- __  TPC_tables
- __ __  23 (pd.DataFrame)
- __ __  24 (pd.DataFrame)
- __ __ ...
- __ SF_table
- __...

I am trying to access the dataframe '23' but I get the following error:
```
file_path=str('/Volumes/Work_Julien/Cell_Data_File/Cell_'+str('504120613')+'_data_file.h5')
current_file = h5py.File(file_path, 'r')
TPC_group = current_file['TPC_tables']
my_dataframe=TPC_group["23"]

Traceback (most recent call last):

  File "/var/folders/jr/1xfz0dmx1c3cgj8rlz1_qrwr0000gn/T/ipykernel_83094/749052623.py", line 4, in <module>
    my_dataframe=TPC_group["23"]

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "/opt/anaconda3/envs/Allen/lib/python3.7/site-packages/h5py/_hl/group.py", line 366, in __getitem__
    return dataset.Dataset(oid, readonly=(self.file.mode == 'r'))

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

TypeError: __init__() got an unexpected keyword argument 'readonly'
```
(Note that I get the same error for any of the object I try to read in the file)
Do you have any idea of the reason for this error?

I am working on MacOS 13.4, with the following python and packages versions:
```
h5py.version.info
'Summary of the h5py configuration\n---------------------------------\n\nh5py    2.10.0\nHDF5    1.10.4\nPython  3.7.13 (default, Mar 28 2022, 07:24:34) \n[Clang 12.0.0 ]\nsys.platform    darwin\nsys.maxsize     9223372036854775807\nnumpy   1.21.6\n'
```

Thank you for any help you can give me!!
Best regards,

Julien

**Comment by tacaswell** [comment]
It looks like the readonly keyword was added in https://github.com/h5py/h5py/commit/773680edcfd868a32a2b047ad654fb3d28da92b2 which is in h5py3.0 , but your version information reports you have 2.10.

My guess is that as part of upgrading you ended up with a chimara environment that has some files from 2.10 and some files from a much newer version (did you use pip on top of conda?). 

I suspect that the "fix" is to re-create your environment (it is rarely worth the effort to debug which packaging has gone wrong....).

**Comment by takluyver** [comment]
Closing as we'll assume this is a corrupted installation; feel free to carry on using the comments if it's useful.
