### ISSUE TITLE
h5 dictionaries can't handle numerical keys 

### ISSUE THREAD

**Issue by yotamcons** [h5py/h5py#2233]
I tried saving a dictionaries in which the keys aren't strings but integers, and got an error. drilling down i saw this repeats for floats.

Working on h5py version 3.8, HDF5 version 1.12.2 run on Python 3.9.16 conda-forge on MacOS 13.2.1

Reproducing:

```
import h5py
f = h5py.File("test.hdf5", "w")
f.attrs.update({1.: 1})
```

stack of error:
```
Traceback (most recent call last):
  File "/Applications/miniconda3/envs/gep-dynamics/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3406, in run_code
    async def run_code(self, code_obj, result=None, *, async_=False):
  File "<ipython-input-37-2a97f1691884>", line 1, in <module>
    f.attrs.update({1.: 1})
  File "/Applications/miniconda3/envs/gep-dynamics/lib/python3.9/_collections_abc.py", line 933, in update
    def update(self, other=(), /, **kwds):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Applications/miniconda3/envs/gep-dynamics/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 96, in __setitem__
    @with_phil
  File "/Applications/miniconda3/envs/gep-dynamics/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 111, in create
    def create(self, name, data, shape=None, dtype=None):
  File "/Applications/miniconda3/envs/gep-dynamics/lib/python3.9/site-packages/h5py/_hl/base.py", line 177, in _e
    def _e(self, name, lcpl=None):
AttributeError: 'float' object has no attribute 'encode'
```

**Comment by tacaswell** [comment]
At the hdf5 layer the keys must be strings (e.g. https://docs.hdfgroup.org/hdf5/develop/group___h5_a.html).  I see a case that we should be raising a better error, but we should definitely not be auto-converting for the users.

**Comment by ajelenak** [comment]
I agree. It may be helpful to understand why the need to store integers and floats as HDF5 attribute names. Perhaps there is way to achieve overall data storage goal with some other approach.

**Comment by yotamcons** [comment]
I'm coming from the agnostic user point of view (specifically I'm using the AnnData package that utilizes h5):
I have a dictionary that I want to save, why should I care about limitations of HDF5 attributes names? I simply have some metadata of interest for me to share.

**Comment by ajelenak** [comment]
Seems to me this is an issue with the AnnData package then. They should probably care what is valid in HDF5.

**Comment by tacaswell** [comment]
Python allow anything hashable to be a dictionary key, where as hdf5 files only support strings.  At the h5py level we try to map as closely to libhdf5's API, while still being "pythonic", as we can.  Thus, when these things are in tension we fallback to following h5 behavior while rhyming with Python's behavior so the behavior here is that keys in `obj.attrs` must be strings (it could be better documented and give better errors).

This has been very successful and keeps h5py as domain-agnostic as possible (I can think of a couple of ways "fix" this problem by turning non-string input into strings, but all of which require making trade-offs that will be wrong at least as often as the are right depending on the context).

I agree with @ajelenak , if you are getting this error through `AnnData` I suggest you take this up with them and they can decide what the "correct" domain-specific way to deal with this impedance miss-match is.

------

Related, even though Python allows it, you really should not use floats as dictionary keys.  It can lead to confusing behavior:


```
In [1]: .3 == .1*3
Out[1]: False

In [2]: hash(.3) == hash(.1*3)
Out[2]: False

In [3]: {.3: 'bob'}[.1*3]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 {.3: 'bob'}[.1*3]

KeyError: 0.30000000000000004
```

**Comment by jangarrevoet** [comment]
I totally agree. I would not like to see in h5py what JSON does, which converts none string keys to strings. Meaning that if you load it again that the key is not there any more or even overwrites other data.
```
In [6]: json.dumps({1:1, "1": 2})
Out[6]: '{"1": 1, "1": 2}'

In [7]: json.loads(json.dumps({1:1, "1": 2}))
Out[7]: {'1': 2}
```

**Comment by takluyver** [comment]
I've marked this as 'good first issue' for improving the error message. h5py isn't going to start accepting non-string keys (though of course a higher-level library like anndata could decide on its own convention for this).

I think anything that accepts a `str` key in h5py also accepts `bytes`, because it's all encoded to bytes to pass to HDF5 anyway. We shouldn't break using `bytes` in these scenarios.

Here's an existing type check and error message for getting keys from a group or file:

https://github.com/h5py/h5py/blob/3507819de54b35af05b2ca8ca55ec7e7b60cb919/h5py/_hl/group.py#L352-L360
